version: '3.3'
services:

    redis:
        image: "bitnami/redis:latest"
        container_name: quotes-redis
        ports:
          - "6379:6379"
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
        networks:
            - unicorn
            
networks:
    unicorn:
        driver: bridge

